require 'rubygems'
require 'test/unit'
require File.dirname(__FILE__) + '/config/connection'
require File.dirname(__FILE__) + '/helpers/providers'
require File.dirname(__FILE__) + '/helpers/set_provider'
require File.dirname(__FILE__) + '/helpers/transactional_test_case'
