name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.6', 'jruby-9.3.0.0']
        gemfile:
          - rails_60
          - rails_61
        include:
          - ruby-version: 2.7.6
            gemfile: rails_70
          - ruby-version: 3.1.5
            gemfile: rails_71

    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v2
      - name: Add --no-document option to .gemrc file to speed up bundle install
        run: "echo 'gem: --no-document' > ~/.gemrc"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run CI task
        run: bundle exec rake
